[package]
name = "rustychip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustychip_core = { path = "../rustychip_core" }
sdl2 = "0.37.0"
clap = { version = "4.5.20", features = ["derive"] }